In [1]:
import pandas as pd
import numpy as np
import re
from datetime import datetime

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest

In [3]:
CLASSIFICATION = True

CLASSIFICATION

True

In [4]:
if not CLASSIFICATION:
    from sklearn.linear_model import LinearRegression as lr
    from sklearn.ensemble import RandomForestRegressor as rf
    from sklearn.svm import SVR as sv
    from sklearn.neighbors import KNeighborsRegressor as knn

    from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error

In [5]:
if CLASSIFICATION:
    from sklearn.preprocessing import LabelEncoder

    from sklearn.linear_model import LogisticRegressionCV as lr
    from sklearn.ensemble import RandomForestClassifier as rf
    from sklearn.svm import SVC as sv
    from sklearn.neighbors import KNeighborsClassifier as knn

    from sklearn.metrics import confusion_matrix, precision_recall_fscore_support, ConfusionMatrixDisplay, classification_report

In [6]:
import matplotlib.pyplot as plt

In [7]:
from utils import evaluate_model_performance

In [8]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

y = a1x1 + a2x2 + a3x3 

In [9]:
from sklearn.datasets import load_iris

In [10]:
X, y = load_iris(return_X_y=True, as_frame=True)

X.shape
y.shape

(150, 4)

(150,)

In [11]:
X.columns = ['sepal_len', 'sepal_wid', 'petal_len', 'petal_wid']
X.head(3)

sepal_len  sepal_wid  petal_len  petal_wid
0        5.1        3.5        1.4        0.2
1        4.9        3.0        1.4        0.2
2        4.7        3.2        1.3        0.2

# Split dataset into training and validation

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)

(X_train.shape, y_train.shape)

(X_test.shape, y_test.shape)

((135, 4), (135,))

((15, 4), (15,))

In [13]:
if CLASSIFICATION:
    enc = LabelEncoder()
    y_train_enc = enc.fit_transform(y_train)

    y_train_enc.shape
    enc.classes_

(135,)

array([0, 1, 2])

# Model Training

models = {
    'LR': LinearRegression(n_jobs=-1),
    'RF': RandomForestRegressor(n_jobs=-1, random_state=0),
    'SVR': SVR(),
    'KNN': KNeighborsRegressor(),
}

In [14]:
models = {
    'LR': lr(n_jobs=-1),
    'RF': rf(n_jobs=-1, random_state=0),
    'SVR': sv(),
    'KNN': knn(),
}

In [15]:
model = models['LR']

if CLASSIFICATION:
    model.fit(X_train, y_train_enc)

if not CLASSIFICATION:
    model.fit(X_train, y_train)

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://sciki

LogisticRegressionCV(n_jobs=-1)

In [16]:
if not CLASSIFICATION:
    
    error_train = mean_absolute_percentage_error(y_train, y_train_pred)
    error_test = mean_absolute_percentage_error(y_test, y_test_pred)

    print(f"error on training set: {error_train:.4f}")
    print(f"error on validation set: {error_test:.4f}")

In [17]:
if CLASSIFICATION:
    y_train_pred = enc.inverse_transform(y_train_pred)
    y_test_pred = enc.inverse_transform(y_test_pred)
    
    confusion_matrix(y_train, y_train_pred)
    confusion_matrix(y_test, y_test_pred)

array([[47,  0,  0],
       [ 0, 39,  3],
       [ 0,  2, 44]])

array([[3, 0, 0],
       [0, 8, 0],
       [0, 0, 4]])

fig, ax = plt.subplots(1,2)
fig.set_figheight(8)
fig.set_figwidth(12)
ax[0].plot(y_train, y_train_pred, c='g', label='mape')
ax[0].set_title("Error on training set")
ax[0].legend()
ax[1].plot(y_test, y_test_pred, c='b', label='mape')
ax[1].set_title("Error on validation set")
ax[1].legend()
plt.show();


{f"{k:.2f}": f"{v:.2f}" for k,v in zip([beta1, beta2, beta3], model.coef_)}