In [1]:
import numpy as np

In [2]:
# multiple prints in a single cell
from IPython.core.interactiveshell import InteractiveShell 
InteractiveShell.ast_node_interactivity = 'all'

In [3]:
mylist = [1,2,3,
         4,5,6,
         7,8,9]

# Handling array of ONE dimension

In [4]:
array0 = np.array(mylist)
array0

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
array0[3]

4

In [6]:
array0[-1]
array0[-2]

9

8

In [7]:
array0[:-2]

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
array0[-2:]

array([8, 9])

In [9]:
array0[-3:-1]

array([7, 8])

# Handling arrays of MULTIPLE dimensions

In [10]:
array1 = np.arange(27).reshape(9,3)
array1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [11]:
array1[1]

array([3, 4, 5])

In [12]:
array1[-3:]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [13]:
array1[3][1]

10

In [14]:
array1[-3:-1]
array1[-3:-1][-2:]
array1[-3:-1][1][-2:]

array([[18, 19, 20],
       [21, 22, 23]])

array([[18, 19, 20],
       [21, 22, 23]])

array([22, 23])

In [15]:
array1[-3:, ]
array1[-3:, 1]
array1[-3:, 1][1:]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

array([19, 22, 25])

array([22, 25])

In [16]:
# select first two items from every row until row 1 inclusive
array1[1:,:2]

array([[ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13],
       [15, 16],
       [18, 19],
       [21, 22],
       [24, 25]])

In [17]:
array1[:2]

array([[0, 1, 2],
       [3, 4, 5]])

# Conditional filters 

In [20]:
# grab all the even numbers from an array

array0
array0[array0%2 ==0]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([2, 4, 6, 8])

In [21]:
# grab all numbers > 5 & < 8

array0
array0[(array0 >5) & (array0 < 8)]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([6, 7])

# argmin & argmax functions 

In [25]:
array1.argmin()
array1.argmax()

0

26