In [ ]:
# ---------------------------------------------------------------
# python best courses https://courses.tanpham.org/
# ---------------------------------------------------------------
# Write a Python program which takes two digits m (row) and n (column) as input and generates a two-dimensional array. 
# The element value in the i-th row and j-th column of the array should be i*j.
# Note :
# i = 0,1.., m-1 
# j = 0,1, n-1.

# Input
# Input number of rows: 3                                                                                       
# Input number of columns: 4  

# Output
# [[0, 0, 0, 0], [0, 1, 2, 3], [0, 2, 4, 6]] 

In [42]:
row_num = int(input('Enter number of rows: '))
col_num = int(input('Enter number of columns: '))

Enter number of rows: 3
Enter number of columns: 4


In [46]:
import numpy as np
my_array = np.zeros((row_num, col_num), dtype = int)
# my_array = [[0 for col in range(col_num)] for row in range(row_num)]
my_array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [47]:
for row in range(row_num):
    for col in range(col_num):
        my_array[row][col] = row*col
print(my_array)

[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]]
